In [10]:
import pandas as pd

In [11]:
df = pd.read_parquet("/Users/ejowik001/Desktop/Github/Nowcasting/kedro/refinery/data/01_raw/vintage_data.parquet")
freq_details = pd.read_csv("/Users/ejowik001/Desktop/Github/Nowcasting/kedro/refinery/data/02_intermediate/series_freq_details.csv")

In [12]:
df_wide = df.pivot(columns="VariableCode", values="VariableValue", index="ReferenceDate")

In [16]:
df_transf = pd.read_parquet("/Users/ejowik001/Desktop/Github/Nowcasting/kedro/refinery/data/02_intermediate/transformed_data.parquet")

In [19]:
freq_details

         VariableCode FrequencyDescription Frequency
0      ACTLISCOU10100              Monthly         m
1       ACTLISCOUMMUS              Monthly         m
2         ACTLISCOUUS              Monthly         m
3       ACTLISCOUYYUS              Monthly         m
4       AVELISPRIMMUS              Monthly         m
...               ...                  ...       ...
10534  LEU0254505100Q            Quarterly         q
10535  LEU0254603600Q            Quarterly         q
10536  LEU0252882500Q            Quarterly         q
10537   WILL5000INDFC         Daily, Close       NaN
10538     ROWSLAQ027S            Quarterly         q

[10539 rows x 3 columns]

In [20]:
freq_details.columns = map(str.lower, freq_details.columns)

In [21]:
freq_details

         variablecode frequencydescription frequency
0      ACTLISCOU10100              Monthly         m
1       ACTLISCOUMMUS              Monthly         m
2         ACTLISCOUUS              Monthly         m
3       ACTLISCOUYYUS              Monthly         m
4       AVELISPRIMMUS              Monthly         m
...               ...                  ...       ...
10534  LEU0254505100Q            Quarterly         q
10535  LEU0254603600Q            Quarterly         q
10536  LEU0252882500Q            Quarterly         q
10537   WILL5000INDFC         Daily, Close       NaN
10538     ROWSLAQ027S            Quarterly         q

[10539 rows x 3 columns]

In [ ]:
def prepare_auto_spec(df):
    """
    Load model specification for a dynamic factor model (DFM).

    Parameters:
    - specfile: str, path to the Excel file containing the model specification.

    Returns:
    - spec: dict, containing the model specification.
    """
    raw_data = df.copy()
    # Convert all headers to lowercase for consistency
    raw_data.columns = raw_data.columns.str.lower()

    # Initialize spec dictionary
    spec = {}

    # Fields to extract from the Excel file
    field_names = ['seriesid', 'frequency', 'transformation']
    for field in field_names:
        if field in raw_data.columns:
            spec[field] = raw_data[field].tolist()
        else:
            raise ValueError(f"{field} column missing from model specification.")

    return spec